data = {
  'status': True,
  'itemsCount': 47,
  'records': [
    {
      'id': '459407',
      'url': '/nemovitosti-byty-domy/459407-nabidka-pronajem-bytu-kladenska-praha',
      'uri': '459407-nabidka-pronajem-bytu-kladenska-praha',
      'reserved': False,
      'highlight': False,
      'short': 'Pronájem bytu 2+1, 54 m²',
      'address': 'Kladenská, Praha - Vokovice',
      'price': '12.500 Kč + 3.900 Kč ',
      'userVerified': False,
      'ideveloper': False,
      'mainImageUrl': 'https://media.bezrealitky.cz/media/cache/record_thumb/data/record/images/459k/459407/1485688669-nzctj-sam-1797.jpg',
      'imageCount': 14,
      'state': False
    },
    {
      'id': '459072',
      'url': '/nemovitosti-byty-domy/459072-nabidka-pronajem-bytu-stanislava-kostky-neumanna-praha',
      'uri': '459072-nabidka-pronajem-bytu-stanislava-kostky-neumanna-praha',
      'reserved': False,
      'highlight': False,
      'short': 'Pronájem bytu 2+1, 54 m²',
      'address': 'Stanislava Kostky Neumanna, Praha - Libeň',
      'price': '14.000 Kč + 4.000 Kč ',
      'userVerified': False,
      'ideveloper': False,
      'mainImageUrl': 'https://media.bezrealitky.cz/media/cache/record_thumb/data/record/images/459k/459072/1485443545-owjyn-kuchyn-204.jpg',
      'imageCount': 4,
      'state': False
    },
    {
      'id': '458767',
      'url': '/nemovitosti-byty-domy/458767-nabidka-pronajem-bytu-na-vaclavce-praha',
      'uri': '458767-nabidka-pronajem-bytu-na-vaclavce-praha',
      'reserved': False,
      'highlight': False,
      'short': 'Pronájem bytu 2+kk, 69 m²',
      'address': 'Na Václavce, Praha - Smíchov',
      'price': '10.000 Kč + 2.000 Kč ',
      'userVerified': False,
      'ideveloper': False,
      'mainImageUrl': 'https://media.bezrealitky.cz/media/cache/record_thumb/data/record/images/458k/458767/1485336338-apnkc-img-3682.jpeg',
      'imageCount': 3,
      'state': False
    },
    {
      'id': '458727',
      'url': '/nemovitosti-byty-domy/458727-nabidka-pronajem-bytu-krymska-praha',
      'uri': '458727-nabidka-pronajem-bytu-krymska-praha',
      'reserved': False,
      'highlight': True,
      'short': 'Pronájem bytu 2+1, 78 m²',
      'address': 'Krymská, Praha - Vršovice',
      'price': '14.800 Kč + 600 Kč ',
      'userVerified': False,
      'ideveloper': False,
      'mainImageUrl': 'https://media.bezrealitky.cz/media/cache/record_thumb/data/record/images/458k/458727/1485291974-mmdmz-img-0284-1.JPG',
      'imageCount': 6,
      'state': False
    },
    {
      'id': '458666',
      'url': '/nemovitosti-byty-domy/458666-nabidka-pronajem-bytu-na-dionysce-praha',
      'uri': '458666-nabidka-pronajem-bytu-na-dionysce-praha',
      'reserved': False,
      'highlight': False,
      'short': 'Pronájem bytu 2+1, 66 m²',
      'address': 'Na Dionysce, Praha - Dejvice',
      'price': '15.000 Kč + 3.500 Kč ',
      'userVerified': True,
      'ideveloper': False,
      'mainImageUrl': 'https://media.bezrealitky.cz/media/cache/record_thumb/data/record/images/458k/458666/1485276387-shwwf-3.jpg',
      'imageCount': 10,
      'state': False
    },
    {
      'id': '458639',
      'url': '/nemovitosti-byty-domy/458639-nabidka-pronajem-bytu-nad-cihelnou-praha',
      'uri': '458639-nabidka-pronajem-bytu-nad-cihelnou-praha',
      'reserved': True,
      'highlight': False,
      'short': 'Pronájem bytu 2+1, 60 m²',
      'address': 'Nad Cihelnou, Praha - Podolí',
      'price': '13.000 Kč + 3.500 Kč ',
      'userVerified': False,
      'ideveloper': False,
      'mainImageUrl': 'https://media.bezrealitky.cz/media/cache/record_thumb/data/record/images/458k/458639/1485268077-upmod-dscn1248.JPG',
      'imageCount': 8,
      'state': False
    },
    {
      'id': '458540',
      'url': '/nemovitosti-byty-domy/458540-nabidka-pronajem-bytu-moskevska-praha',
      'uri': '458540-nabidka-pronajem-bytu-moskevska-praha',
      'reserved': False,
      'highlight': False,
      'short': 'Pronájem bytu 2+1, 58 m²',
      'address': 'Moskevská, Praha - Vršovice',
      'price': '16.000 Kč + 2.000 Kč ',
      'userVerified': False,
      'ideveloper': False,
      'mainImageUrl': 'https://media.bezrealitky.cz/media/cache/record_thumb/data/record/images/458k/458540/1485197025-vytym-img-4055.JPG',
      'imageCount': 8,
      'state': False
    },
    {
      'id': '458458',
      'url': '/nemovitosti-byty-domy/458458-nabidka-pronajem-bytu-na-strelnici-praha',
      'uri': '458458-nabidka-pronajem-bytu-na-strelnici-praha',
      'reserved': False,
      'highlight': False,
      'short': 'Pronájem bytu 2+1, 53 m²',
      'address': 'Na Střelnici, Praha - Karlín',
      'price': '11.000 Kč + 1.000 Kč ',
      'userVerified': False,
      'ideveloper': False,
      'mainImageUrl': 'https://media.bezrealitky.cz/media/cache/record_thumb/data/record/images/458k/458458/1485182013-xqjua-20160530-090530.jpg',
      'imageCount': 5,
      'state': False
    },
    {
      'id': '458403',
      'url': '/nemovitosti-byty-domy/458403-nabidka-pronajem-bytu-plzenska-praha',
      'uri': '458403-nabidka-pronajem-bytu-plzenska-praha',
      'reserved': False,
      'highlight': False,
      'short': 'Pronájem bytu 2+kk, 53 m²',
      'address': 'Plzeňská, Praha - Smíchov',
      'price': '13.000 Kč + 1.500 Kč ',
      'userVerified': False,
      'ideveloper': False,
      'mainImageUrl': 'https://media.bezrealitky.cz/media/cache/record_thumb/data/record/images/458k/458403/1485166935-lpqwi-20161130-113542.jpg',
      'imageCount': 2,
      'state': False
    },
    {
      'id': '458294',
      'url': '/nemovitosti-byty-domy/458294-nabidka-pronajem-bytu-evropska-praha',
      'uri': '458294-nabidka-pronajem-bytu-evropska-praha',
      'reserved': False,
      'highlight': False,
      'short': 'Pronájem bytu 2+kk, 58 m²',
      'address': 'Evropská, Praha - Dejvice',
      'price': '13.500 Kč + 4.400 Kč ',
      'userVerified': False,
      'ideveloper': False,
      'mainImageUrl': 'https://media.bezrealitky.cz/media/cache/record_thumb/data/record/images/458k/458294/1485097900-yixkm-20131213-143623.jpg',
      'imageCount': 9,
      'state': False
    },
    {
      'id': '457883',
      'url': '/nemovitosti-byty-domy/457883-nabidka-pronajem-bytu-cajkovskeho-praha',
      'uri': '457883-nabidka-pronajem-bytu-cajkovskeho-praha',
      'reserved': False,
      'highlight': False,
      'short': 'Pronájem bytu 2+1, 55 m²',
      'address': 'Čajkovského, Praha - Žižkov',
      'price': '16.000 Kč + 2.000 Kč ',
      'userVerified': False,
      'ideveloper': False,
      'mainImageUrl': 'https://media.bezrealitky.cz/media/cache/record_thumb/data/record/images/457k/457883/1484818202-exehq-bathroom.PNG',
      'imageCount': 13,
      'state': False
    },
    {
      'id': '457778',
      'url': '/nemovitosti-byty-domy/457778-nabidka-pronajem-bytu-komunardu-praha',
      'uri': '457778-nabidka-pronajem-bytu-komunardu-praha',
      'reserved': True,
      'highlight': False,
      'short': 'Pronájem bytu 2+kk, 55 m²',
      'address': 'Komunardů, Praha - Holešovice',
      'price': '15.000 Kč + 3.000 Kč ',
      'userVerified': False,
      'ideveloper': False,
      'mainImageUrl': 'https://media.bezrealitky.cz/media/cache/record_thumb/data/record/images/457k/457778/1484744975-cegep-living-room.jpg',
      'imageCount': 9,
      'state': False
    },
    {
      'id': '457689',
      'url': '/nemovitosti-byty-domy/457689-nabidka-pronajem-bytu-obloukova-praha',
      'uri': '457689-nabidka-pronajem-bytu-obloukova-praha',
      'reserved': True,
      'highlight': False,
      'short': 'Pronájem bytu 2+kk, 55 m²',
      'address': 'Oblouková, Praha - Vršovice',
      'price': '13.500 Kč + 2.500 Kč ',
      'userVerified': False,
      'ideveloper': False,
      'mainImageUrl': 'https://media.bezrealitky.cz/media/cache/record_thumb/data/record/images/457k/457689/1484685804-nppjg-koupelna.jpg',
      'imageCount': 11,
      'state': False
    },
    {
      'id': '457605',
      'url': '/nemovitosti-byty-domy/457605-nabidka-pronajem-bytu-heralecka-iii-praha',
      'uri': '457605-nabidka-pronajem-bytu-heralecka-iii-praha',
      'reserved': False,
      'highlight': False,
      'short': 'Pronájem bytu 2+1, 52 m²',
      'address': 'Herálecká III, Praha - Krč',
      'price': '15.000 Kč + 3.000 Kč ',
      'userVerified': False,
      'ideveloper': False,
      'mainImageUrl': 'https://media.bezrealitky.cz/media/cache/record_thumb/data/record/images/457k/457605/1484658598-xvzom-kuchyne.JPG',
      'imageCount': 6,
      'state': False
    },
    {
      'id': '457216',
      'url': '/nemovitosti-byty-domy/457216-nabidka-pronajem-bytu-vltavska-praha',
      'uri': '457216-nabidka-pronajem-bytu-vltavska-praha',
      'reserved': False,
      'highlight': False,
      'short': 'Pronájem bytu 2+1, 56 m²',
      'address': 'Vltavská, Praha - Smíchov',
      'price': '16.000 Kč',
      'userVerified': False,
      'ideveloper': False,
      'mainImageUrl': 'https://media.bezrealitky.cz/media/cache/record_thumb/data/record/images/457k/457216/1484435906-tmdbn-20170114-141314.jpg',
      'imageCount': 7,
      'state': False
    },
    {
      'id': '456431',
      'url': '/nemovitosti-byty-domy/456431-nabidka-pronajem-bytu-kalisnicka-praha',
      'uri': '456431-nabidka-pronajem-bytu-kalisnicka-praha',
      'reserved': False,
      'highlight': False,
      'short': 'Pronájem bytu 2+kk, 66 m²',
      'address': 'Kališnická, Praha - Žižkov',
      'price': '16.000 Kč + 5.700 Kč ',
      'userVerified': False,
      'ideveloper': False,
      'mainImageUrl': 'https://media.bezrealitky.cz/media/cache/record_thumb/data/record/images/456k/456431/1483951932-bcxbd-k1.jpeg',
      'imageCount': 7,
      'state': False
    },
    {
      'id': '456356',
      'url': '/nemovitosti-byty-domy/456356-nabidka-pronajem-bytu-na-plani-praha',
      'uri': '456356-nabidka-pronajem-bytu-na-plani-praha',
      'reserved': False,
      'highlight': False,
      'short': 'Pronájem bytu 2+1, 55 m²',
      'address': 'Na Pláni, Praha - Smíchov',
      'price': '13.500 Kč',
      'userVerified': False,
      'ideveloper': False,
      'mainImageUrl': 'https://media.bezrealitky.cz/media/cache/record_thumb_placeholder/web/web/img/placeholders/default_foto_main.gif',
      'imageCount': 0,
      'state': False
    },
    {
      'id': '456254',
      'url': '/nemovitosti-byty-domy/456254-nabidka-pronajem-bytu-preslova-praha',
      'uri': '456254-nabidka-pronajem-bytu-preslova-praha',
      'reserved': True,
      'highlight': False,
      'short': 'Pronájem bytu 2+1, 53 m²',
      'address': 'Preslova, Praha - Smíchov',
      'price': '15.500 Kč + 600 Kč ',
      'userVerified': False,
      'ideveloper': False,
      'mainImageUrl': 'https://media.bezrealitky.cz/media/cache/record_thumb/data/record/images/456k/456254/1483807444-khfwd-img-6260.JPG',
      'imageCount': 8,
      'state': False
    },
    {
      'id': '456222',
      'url': '/nemovitosti-byty-domy/456222-nabidka-pronajem-bytu-evropska-praha',
      'uri': '456222-nabidka-pronajem-bytu-evropska-praha',
      'reserved': True,
      'highlight': False,
      'short': 'Pronájem bytu 2+1, 65 m²',
      'address': 'Evropská, Praha - Dejvice',
      'price': '13.000 Kč + 2.500 Kč ',
      'userVerified': False,
      'ideveloper': False,
      'mainImageUrl': 'https://media.bezrealitky.cz/media/cache/record_thumb/data/record/images/456k/456222/1483791441-mcied-kuchynska-linka.jpg',
      'imageCount': 11,
      'state': False
    },
    {
      'id': '456128',
      'url': '/nemovitosti-byty-domy/456128-nabidka-pronajem-bytu-antala-staska-praha',
      'uri': '456128-nabidka-pronajem-bytu-antala-staska-praha',
      'reserved': False,
      'highlight': False,
      'short': 'Pronájem bytu 2+1, 58 m²',
      'address': 'Antala Staška, Praha - Krč',
      'price': '10.000 Kč + 3.500 Kč ',
      'userVerified': False,
      'ideveloper': False,
      'mainImageUrl': 'https://media.bezrealitky.cz/media/cache/record_thumb_placeholder/web/web/img/placeholders/default_foto_main.gif',
      'imageCount': 0,
      'state': False
    }
  ]
}
